# Generated by Django 3.2.7 on 2023-06-01 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
        ('creator', '0001_initial'),
        ('service', '0001_initial'),
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='punish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punishSum', models.IntegerField()),
                ('status', models.CharField(choices=[('unHandle', '未处理'), ('handled', '已处理')], max_length=20)),
                ('pId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punish_pId', to='service.problem')),
                ('staffId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.staff')),
            ],
        ),
        migrations.CreateModel(
            name='point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trasaction', models.IntegerField()),
                ('status', models.CharField(choices=[('settle', '结算中'), ('withdraw', '提现中'), ('over', '已完成')], default=1, max_length=20)),
                ('pDate', models.DateTimeField(null=True)),
                ('cId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_cId', to='creator.creator')),
                ('staffId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.staff')),
                ('taskId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_taskId', to='creator.task')),
                ('wId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_wId', to='worker.worker')),
            ],
        ),
    ]
