# Generated by Django 3.2.7 on 2023-06-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_point_fintime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='status',
            field=models.CharField(choices=[('settle', '结算中'), ('withdraw', '提现中'), ('punish', '处罚中'), ('over', '已完成')], default=1, max_length=20),
        ),
    ]
