# Generated by Django 3.2.7 on 2023-06-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_point_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[('reward', '任务奖励'), ('fill', '充值'), ('punish', '惩罚')], default='reward', max_length=20),
        ),
    ]
