# Generated by Django 3.2.7 on 2023-06-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_point_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='status',
            field=models.CharField(choices=[('settle', '结算中'), ('withdraw', '提现中'), ('punish', '处罚中'), ('compensate', '补偿'), ('over', '已完成')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[('reward', '任务奖励'), ('fill', '充值'), ('punish', '惩罚'), ('compensate', '补偿')], default='reward', max_length=20),
        ),
    ]
