# Generated by Django 3.2.7 on 2023-06-03 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_problem_punish'),
        ('finance', '0005_auto_20230603_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='pId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.problem'),
        ),
    ]
