# Generated by Django 3.2.7 on 2023-06-01 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='creator',
            fields=[
                ('cId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('pwd', models.CharField(max_length=16)),
                ('point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='data',
            fields=[
                ('dId', models.AutoField(primary_key=True, serialize=False)),
                ('dLink', models.URLField(max_length=100, null=True)),
                ('dType', models.CharField(choices=[('word', '文字'), ('pic', '图片'), ('video', '视频')], max_length=20)),
                ('dFile', models.BinaryField(null=True)),
                ('description', models.TextField(null=True)),
                ('cId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.creator')),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('taskId', models.AutoField(primary_key=True, serialize=False)),
                ('taskName', models.CharField(default=None, max_length=200)),
                ('cover', models.BinaryField(null=True)),
                ('taskContent', models.TextField()),
                ('taskDescription', models.BinaryField(null=True)),
                ('createTime', models.DateTimeField(null=True)),
                ('taskType', models.CharField(choices=[('textClean', '文本清洗'), ('emotionLable', '情感标注'), ('textClass', '文本分类'), ('semanticSeg', '语义分割'), ('picClass', '图片分类')], max_length=20)),
                ('taskLimit', models.DateTimeField(max_length=20)),
                ('deleted', models.BooleanField(default=False)),
                ('reward', models.CharField(default=0, max_length=20)),
                ('status', models.CharField(choices=[('rChecking', '发布审核中'), ('unpass', '审核未通过'), ('unAccept', '未被接受'), ('labeling', '标注中'), ('checking', '审核中'), ('over', '已完成'), ('cancel', '已取消')], default='rChecking', max_length=20)),
                ('lastUpdate', models.DateTimeField(default='2023-05-01 00:00:00')),
                ('cId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.creator')),
                ('dId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='creator.data')),
            ],
        ),
        migrations.CreateModel(
            name='problem',
            fields=[
                ('pId', models.AutoField(primary_key=True, serialize=False)),
                ('pName', models.CharField(max_length=40, null=True)),
                ('pContent', models.TextField()),
                ('subTime', models.DateTimeField()),
                ('type', models.CharField(choices=[('taskResult', '任务审核结果申诉'), ('taskReward', '任务奖励发放申诉'), ('account', '个人账户信息申诉'), ('labelSystem', '标注系统异常申诉')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('unHandle', '未处理'), ('handled', '已处理')], max_length=20)),
                ('feedBack', models.TextField(null=True)),
                ('finTime', models.DateTimeField(null=True)),
                ('cId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_cId', to='creator.creator')),
                ('taskId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cproblem_taskId', to='creator.task')),
            ],
        ),
        migrations.CreateModel(
            name='checkTask',
            fields=[
                ('checkId', models.AutoField(primary_key=True, serialize=False)),
                ('subTime', models.DateTimeField()),
                ('checkResult', models.CharField(choices=[('good', '优质'), ('pass', '通过'), ('low', '低质'), ('unpass', '未通过')], max_length=20, null=True)),
                ('finTime', models.DateTimeField(default=None, null=True)),
                ('checkType', models.CharField(choices=[('labelTryCheck', '试标注审核'), ('labelCheck', '标注审核')], max_length=20)),
                ('cId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.creator')),
                ('taskId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.task')),
            ],
        ),
    ]
