# Generated by Django 3.2.7 on 2023-06-03 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_rename_pid_problem_cpid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='cId',
        ),
        migrations.RemoveField(
            model_name='task',
            name='dId',
        ),
        migrations.AddField(
            model_name='data',
            name='taskId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creator.task'),
        ),
    ]
