# Generated by Django 3.2.7 on 2023-06-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0003_auto_20230603_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskType',
            field=models.CharField(choices=[('textClean', '文本清洗'), ('emotionLable', '情感标注'), ('textClass', '文本分类'), ('semanticSeg', '语义分割'), ('picClass', '图片分类'), ('objectDetection', '目标检测')], max_length=20),
        ),
    ]
