# Generated by Django 3.2.7 on 2023-06-01 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
        ('creator', '0001_initial'),
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='release_task_check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subTime', models.DateTimeField()),
                ('checkResult', models.CharField(choices=[('pass', '通过'), ('unpass', '未通过')], max_length=20, null=True)),
                ('feedBack', models.TextField(null=True)),
                ('finTime', models.DateTimeField(null=True)),
                ('staffId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.staff')),
                ('taskId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.task')),
            ],
        ),
        migrations.CreateModel(
            name='problem',
            fields=[
                ('pId', models.AutoField(primary_key=True, serialize=False)),
                ('pName', models.CharField(max_length=40, null=True)),
                ('pContent', models.TextField()),
                ('subTime', models.DateTimeField()),
                ('type', models.CharField(choices=[('taskResult', '任务审核结果申诉'), ('taskReward', '任务奖励发放申诉'), ('account', '个人账户信息申诉'), ('labelSystem', '标注系统异常申诉')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('unHandle', '未处理'), ('handled', '已处理')], max_length=20)),
                ('feedBack', models.TextField(null=True)),
                ('punish', models.IntegerField(choices=[('unpunish', '不处罚'), ('punish', '处罚'), ('compensate', '补偿')], null=True)),
                ('finTime', models.DateTimeField(null=True)),
                ('cId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creator.creator')),
                ('staffId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.staff')),
                ('taskId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staskId', to='creator.task')),
                ('wId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='worker.worker')),
            ],
        ),
    ]
