# Generated by Django 3.2.7 on 2023-06-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='punish',
            field=models.CharField(choices=[('unpunish', '不处罚'), ('punish', '处罚'), ('compensate', '补偿')], max_length=20, null=True),
        ),
    ]
