# Generated by Django 3.2.7 on 2023-06-01 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='worker',
            fields=[
                ('wId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('pwd', models.CharField(max_length=16)),
                ('score', models.FloatField(default=0)),
                ('point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='problem',
            fields=[
                ('pId', models.AutoField(primary_key=True, serialize=False)),
                ('pContent', models.TextField()),
                ('pName', models.CharField(max_length=40, null=True)),
                ('subTime', models.DateTimeField()),
                ('status', models.CharField(choices=[('toHandle', '未处理'), ('handled', '已处理')], max_length=20)),
                ('type', models.CharField(choices=[('taskResult', '任务审核结果申诉'), ('taskReward', '任务奖励发放申诉'), ('account', '个人账户信息申诉'), ('labelSystem', '标注系统异常申诉')], max_length=20, null=True)),
                ('feedBack', models.TextField(null=True)),
                ('finTime', models.DateTimeField(null=True)),
                ('taskId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wproblem_taskId', to='creator.task')),
                ('wId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_wId', to='worker.worker')),
            ],
        ),
        migrations.CreateModel(
            name='labelTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelResult', models.JSONField(null=True)),
                ('status', models.CharField(choices=[('labeling', '标注中'), ('checking', '审核中'), ('over', '已完成')], max_length=20)),
                ('checkResult', models.CharField(choices=[('good', '优质'), ('pass', '通过'), ('low', '低质'), ('unpass', '未通过')], default=None, max_length=20, null=True)),
                ('subTime', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('taskId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.task')),
                ('wId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.worker')),
            ],
        ),
        migrations.CreateModel(
            name='evaluate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('eTime', models.DateTimeField()),
                ('cId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.creator')),
                ('taskId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.task')),
                ('wId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.worker')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('cmId', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('cmTime', models.DateTimeField()),
                ('promoter', models.CharField(choices=[('creator', '任务接受者'), ('worker', '任务发布者')], max_length=20)),
                ('cId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_cId', to='creator.creator')),
                ('taskId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_taskId', to='creator.task')),
                ('wId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_wId', to='worker.worker')),
            ],
        ),
        migrations.CreateModel(
            name='acceptedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptTime', models.DateTimeField()),
                ('status', models.CharField(choices=[('labeling', '标注中'), ('checking', '审核中'), ('changing', '修改中'), ('over', '已完成')], max_length=20)),
                ('finTime', models.DateTimeField(default=None, null=True)),
                ('delete', models.BooleanField(default=0)),
                ('result', models.JSONField(null=True)),
                ('taskId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.task')),
                ('wId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.worker')),
            ],
        ),
    ]
