# Generated by Django 3.2.7 on 2023-06-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='pId',
            new_name='wpId',
        ),
    ]
