# Generated by Django 4.2.1 on 2023-06-03 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0003_auto_20230603_2338"),
        ("worker", "0002_rename_pid_problem_wpid"),
    ]

    operations = [
        migrations.CreateModel(
            name="labels",
            fields=[
                ("lId", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.JSONField()),
                (
                    "taskId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="creator.task",
                    ),
                ),
            ],
        ),
    ]
