# Generated by Django 4.2.1 on 2023-06-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0003_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="labels",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
