# Generated by Django 3.2.7 on 2023-06-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('nId', models.AutoField(primary_key=True, serialize=False)),
                ('noticeName', models.CharField(max_length=50)),
                ('noticeContent', models.TextField()),
                ('noticeFile', models.BinaryField()),
                ('noticeDate', models.DateTimeField()),
                ('public', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
    ]
