# Generated by Django 3.2.7 on 2023-06-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20230601_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
    ]
