# Generated by Django 3.2.7 on 2023-06-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_notice_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='notice',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
